server:
  port: 9009
spring:
  rabbitmq:
    host: 127.0.0.1
  application:
    name: RabbitApplication
aliyun:
  sms:
    accessKeyId: 不告诉你
    accessKeySecret: 不告诉你
    template_code: SMS_85735065
    sign_name: 黑马