server:
  port: 9001
spring:
  profiles:
    active: dev
  application:
    name: tensquare-com.tenquare.base #指定服务名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_base?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password:
  jpa:
    database: MYSQL
    show-sql: true