server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_user?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password:
    jpa:
      database: MySQL
      show-sql: true
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 127.0.0.1
jwt:
  config:
    key: first
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance: #支持模块跨域请求
    prefer-ip-address: true