spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wuzhaoyu/Config-Center.git
  rabbitmq:
    host: 127.0.0.1
server:
  port: 12000
management: #暴露触发消息总线的地址，重新加载配置文件
  endpoints:
    web:
      exposure:
        include: bus-refresh