server:
  port: 9003
spring:
  application:
    name: tensquare-qa #指定服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_qa?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password:
  jpa:
    database: MySQL
    show-sql: true
jwt:
  config:
    key: first