server: 
  port: 9014
spring: 
  application:  
    name: tensquare-article #指定服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_article?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password:
  redis:
    host: 127.0.0.1
    database: 9
  jpa: 
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6660/eureka/
  instance: #支持模块跨域请求
     prefer-ip-address: true